package com.alphapay.payEngine.common.bean;

public enum BackEndServiceNamesConstants {
    TRANSFER,DEBIT,CREDIT,REVERSAL,CIF_DETAILS,GET_ACC_LIST,TRAN_DETAILLS,ACCOUNT_STATEMENT,NATIONAL_REGISTRY,API_LOGIN
    , BENEFICIARY_ACC_LIST, CHEQUE_REDEEM_STATUS,INSTALLMENTS,EXCHANGE_RATE,PUBLIC_KEY,USER_ONBOARDING_ACCOUNT,CHEQUE_REQUEST_STATUS;
}
